spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf-8
    username: root
    password: 250686qaz
#    url: jdbc:mysql://localhost:3306/jf_gateway?useSSL=false&characterEncoding=utf-8
#    username: root
#    password: mysqladmin
#    url: jdbc:mysql://10.20.5.110:3306/jf_gateway_41?useSSL=false&characterEncoding=utf-8
#    username: root
#    password: Jfkjyfb@123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      maxActive: 200
      initialSize: 10
      minIdle: 10
      maxWait: 60000
      validationQuery: "SELECT 'x'"
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 100
#      maxOpenPreparedStatements: 20
      async-init: true
      filter:
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/actuator/*,actuator"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  type-aliases-package: com.springboot.entity.User
